export const types = Object.freeze({
    //Async
    FETCH_TASKS_ASYNC:        'FETCH_TASKS_ASYNC',
    CREATE_TASKS_ASYNC:       'CREATE_TASKS_ASYNC',
    UPDATE_TASKS_ASYNC:       'UPDATE_TASKS_ASYNC',
    REMOVE_TASKS_ASYNC:       'REMOVE_TASKS_ASYNC',
    COMPLETE_ALL_TASKS_ASYNC: 'COMPLETE_ALL_TASKS_ASYNC',

    //Sync
    FILL_TASKS:           'FILL_TASKS',
    CREATE_TASK:          'CREATE_TASK',
    UPDATE_TASKS:         'UPDATE_TASKS',
    REMOVE_TASKS:         'REMOVE_TASKS',
    COMPLETE_ALL_TASKS:   'COMPLETE_ALL_TASKS',
    EDIT_TASK_CHANGE:     'EDIT_TASK_CHANGE',
    EDIT_TASK_FOCUS:      'EDIT_TASK_FOCUS',
    EDIT_TASK_FOCUS:      'EDIT_TASK_FOCUS',

});
